In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

## Create & Read

 #### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

5

#### 2D Array

In [9]:
arr2 = np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

#### 3D array

In [10]:
arr3 = np.array([[[1,4,5],[6,7,4]],[[3,4,5],[5,6,7]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [5, 6, 7]]])

In [11]:
arr3.ndim

3

In [12]:
arr3.shape

(2, 2, 3)